// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/rankings": {
    params: {};
  };
  "/matches": {
    params: {};
  };
  "/groups": {
    params: {};
  };
  "/profile": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/rankings" | "/matches" | "/groups" | "/profile";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/rankings.tsx": {
    id: "routes/rankings";
    page: "/rankings";
  };
  "routes/matches.tsx": {
    id: "routes/matches";
    page: "/matches";
  };
  "routes/groups.tsx": {
    id: "routes/groups";
    page: "/groups";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/rankings": typeof import("./app/routes/rankings.tsx");
  "routes/matches": typeof import("./app/routes/matches.tsx");
  "routes/groups": typeof import("./app/routes/groups.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
};