// Generated by React Router

import "react-router";

declare module "react-router" {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
    routeModules: RouteModules;
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/rankings": {
    params: {};
  };
  "/matches": {
    params: {};
  };
  "/groups": {
    params: {};
  };
  "/profile": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/rankings" | "/matches" | "/groups" | "/profile";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/rankings.tsx": {
    id: "routes/rankings";
    page: "/rankings";
  };
  "routes/matches.tsx": {
    id: "routes/matches";
    page: "/matches";
  };
  "routes/groups.tsx": {
    id: "routes/groups";
    page: "/groups";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
};

type RouteModules = {
  root: typeof import("./src/root.js");
  "routes/_index": typeof import("./src/routes/_index.js");
  "routes/login": typeof import("./src/routes/login.js");
  "routes/rankings": typeof import("./src/routes/rankings.js");
  "routes/matches": typeof import("./src/routes/matches.js");
  "routes/groups": typeof import("./src/routes/groups.js");
  "routes/profile": typeof import("./src/routes/profile.js");
};
